model:
  name: gpt2                 # registry key → ep.models.fpt2.GPT2EdgePruneModel
  checkpoint: gpt2           # any Hugging-Face ID or local path

task:
  name: ioi                  # registry key → ep.tasks.ioi.IOITask
  data_path: data/ioi        # folder containing train.jsonl / validation.jsonl
  split: train               # which split to feed the trainer
  batch_size: 8

optim:
  lr: 1.5e-4
  betas: [0.9, 0.98]
  wd: 0.01
  warmup_steps: 200
  max_steps: 2000
  beta: 1.0e-4              # weight on sparsity loss

seed: 0
log_every: 20
eval_every: 200
output_dir: runs/gpt2_ioi_ep
